<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\InventoryItem;

class InventorySeeder extends Seeder
{
    public function run(): void
    {
        $items = [
            [
                'name' => 'Guantes de látex',
                'description' => 'Guantes estériles desechables talla M',
                'category' => 'insumos',
                'sku' => 'GLO-M-001',
                'quantity' => 120,
                'min_stock' => 30,
                'unit' => 'caja',
                'unit_cost' => 25.00,
                'supplier' => 'MediSupply Perú',
                'location' => 'Almacén',
            ],
            [
                'name' => 'Guantes de nitrilo',
                'description' => 'Guantes de nitrilo sin polvo talla L',
                'category' => 'insumos',
                'sku' => 'GLO-N-L-002',
                'quantity' => 80,
                'min_stock' => 20,
                'unit' => 'caja',
                'unit_cost' => 35.00,
                'supplier' => 'MediSupply Perú',
                'location' => 'Almacén',
            ],
            [
                'name' => 'Mascarillas quirúrgicas',
                'description' => 'Mascarillas de 3 capas color azul',
                'category' => 'insumos',
                'sku' => 'MAS-001',
                'quantity' => 200,
                'min_stock' => 50,
                'unit' => 'caja',
                'unit_cost' => 12.50,
                'supplier' => 'MediSupply Perú',
                'location' => 'Almacén',
            ],
            [
                'name' => 'Baberos desechables',
                'description' => 'Baberos azules con bolsillo frontal',
                'category' => 'insumos',
                'sku' => 'BAB-001',
                'quantity' => 150,
                'min_stock' => 40,
                'unit' => 'paquete',
                'unit_cost' => 8.00,
                'supplier' => 'DentalPro',
                'location' => 'Consultorio 1',
            ],
            [
                'name' => 'Anestésico Lidocaína 2%',
                'description' => 'Carpules de lidocaína con epinefrina',
                'category' => 'medicamentos',
                'sku' => 'ANES-LID-001',
                'quantity' => 40,
                'min_stock' => 10,
                'unit' => 'caja',
                'unit_cost' => 45.00,
                'supplier' => 'FarmaDental',
                'location' => 'Farmacia',
                'expiration_date' => now()->addMonths(12)->toDateString(),
            ],
            [
                'name' => 'Anestésico Articaína 4%',
                'description' => 'Carpules de articaina 1:100000',
                'category' => 'medicamentos',
                'sku' => 'ANES-ART-001',
                'quantity' => 25,
                'min_stock' => 8,
                'unit' => 'caja',
                'unit_cost' => 55.00,
                'supplier' => 'FarmaDental',
                'location' => 'Farmacia',
                'expiration_date' => now()->addMonths(8)->toDateString(),
            ],
            [
                'name' => 'Algodón dental',
                'description' => 'Rollos de algodón puro para odontología',
                'category' => 'insumos',
                'sku' => 'ALG-001',
                'quantity' => 60,
                'min_stock' => 15,
                'unit' => 'bolsa',
                'unit_cost' => 6.50,
                'supplier' => 'DentalPro',
                'location' => 'Almacén',
            ],
            [
                'name' => 'Puntas de aspiración',
                'description' => 'Puntas desechables para succionador',
                'category' => 'insumos',
                'sku' => 'PUN-ASP-001',
                'quantity' => 500,
                'min_stock' => 100,
                'unit' => 'caja',
                'unit_cost' => 18.00,
                'supplier' => 'MediSupply Perú',
                'location' => 'Almacén',
            ],
            [
                'name' => 'Jeringas carpule',
                'description' => 'Jeringas metálicas para carpules de anestesia',
                'category' => 'insumos',
                'sku' => 'JER-CAR-001',
                'quantity' => 10,
                'min_stock' => 3,
                'unit' => 'unidad',
                'unit_cost' => 120.00,
                'supplier' => 'DentalPro',
                'location' => 'Consultorio 1',
            ],
            [
                'name' => 'Turbina dental',
                'description' => 'Turbina de alta velocidad con luz LED',
                'category' => 'equipos',
                'sku' => 'TUR-001',
                'quantity' => 2,
                'min_stock' => 1,
                'unit' => 'unidad',
                'unit_cost' => 850.00,
                'supplier' => 'KaVo Perú',
                'location' => 'Consultorio 1',
            ],
            [
                'name' => 'Micromotor eléctrico',
                'description' => 'Micromotor con contrángulo',
                'category' => 'equipos',
                'sku' => 'MIC-001',
                'quantity' => 2,
                'min_stock' => 1,
                'unit' => 'unidad',
                'unit_cost' => 620.00,
                'supplier' => 'NSK Perú',
                'location' => 'Consultorio 2',
            ],
            [
                'name' => 'Lampara de fotocurado',
                'description' => 'Lampara LED para polimerización',
                'category' => 'equipos',
                'sku' => 'LAM-LED-001',
                'quantity' => 3,
                'min_stock' => 1,
                'unit' => 'unidad',
                'unit_cost' => 320.00,
                'supplier' => 'DentalPro',
                'location' => 'Consultorio 1',
            ],
            [
                'name' => 'Ionómero de vidrio',
                'description' => 'Ionómero de vidrio para restauraciones',
                'category' => 'medicamentos',
                'sku' => 'ION-VID-001',
                'quantity' => 12,
                'min_stock' => 4,
                'unit' => 'caja',
                'unit_cost' => 38.00,
                'supplier' => '3M ESPE',
                'location' => 'Farmacia',
                'expiration_date' => now()->addMonths(18)->toDateString(),
            ],
            [
                'name' => 'Resina compuesta',
                'description' => 'Kit de resina compuesta nanohíbrida',
                'category' => 'medicamentos',
                'sku' => 'RES-NAN-001',
                'quantity' => 8,
                'min_stock' => 3,
                'unit' => 'kit',
                'unit_cost' => 145.00,
                'supplier' => 'Ivoclar Vivadent',
                'location' => 'Farmacia',
                'expiration_date' => now()->addMonths(24)->toDateString(),
            ],
            [
                'name' => 'Hilo retráctor',
                'description' => 'Hilo gingival retráctor #000',
                'category' => 'insumos',
                'sku' => 'HIL-RET-001',
                'quantity' => 15,
                'min_stock' => 5,
                'unit' => 'caja',
                'unit_cost' => 28.00,
                'supplier' => 'DentalPro',
                'location' => 'Almacén',
            ],
            [
                'name' => 'Tiras de articulación',
                'description' => 'Papel de articulación en tiras',
                'category' => 'insumos',
                'sku' => 'TIR-ART-001',
                'quantity' => 30,
                'min_stock' => 10,
                'unit' => 'caja',
                'unit_cost' => 14.00,
                'supplier' => 'Bausch Dental',
                'location' => 'Almacén',
            ],
            [
                'name' => 'Papel cefálico',
                'description' => 'Papel para impresiones cefálicas',
                'category' => 'insumos',
                'sku' => 'PAF-CEF-001',
                'quantity' => 20,
                'min_stock' => 5,
                'unit' => 'rollo',
                'unit_cost' => 22.00,
                'supplier' => 'DentalPro',
                'location' => 'Almacén',
            ],
            [
                'name' => 'Desinfectante instrumental',
                'description' => 'Solución desinfectante para instrumentos',
                'category' => 'medicamentos',
                'sku' => 'DES-INS-001',
                'quantity' => 6,
                'min_stock' => 2,
                'unit' => 'frasco',
                'unit_cost' => 42.00,
                'supplier' => 'Medichem',
                'location' => 'Almacén',
                'expiration_date' => now()->addMonths(6)->toDateString(),
            ],
            [
                'name' => 'Kit de profilaxis',
                'description' => 'Kit completo para profilaxis dental',
                'category' => 'insumos',
                'sku' => 'KIT-PRO-001',
                'quantity' => 50,
                'min_stock' => 15,
                'unit' => 'kit',
                'unit_cost' => 9.50,
                'supplier' => 'DentalPro',
                'location' => 'Consultorio 1',
            ],
            [
                'name' => 'Radiovisiografo sensor',
                'description' => 'Sensor digital intraoral RVG',
                'category' => 'equipos',
                'sku' => 'RVG-SEN-001',
                'quantity' => 1,
                'min_stock' => 1,
                'unit' => 'unidad',
                'unit_cost' => 3500.00,
                'supplier' => 'Vatech Perú',
                'location' => 'Rayos X',
            ],
        ];

        foreach ($items as $item) {
            InventoryItem::create($item);
        }
    }
}
